name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Build audit tools
        run: |
          go build ./cmd/mcp-audit-wrap
          go build ./cmd/mcp-audit-proxy

      - name: Install test deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq bc file

      - name: Run E2E (offline, SKIP-friendly)
        run: |
          bash test/e2e/basic/test_mcp_audit_basics.sh || true
          bash test/e2e/attack/test_mcp_anomalies.sh || true
